Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.unir.hanlers.CattleHandler
      CodeUri: E:\UnirAWS
      Runtime: java17
      Architectures:
        - x86_64